server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: 'optional:consul:'
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: 'sa'
    password: 'password'
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    topic: orders

management:
  security:
    enabled: false

springdoc:
  api-docs:
    path: '/api-docs'